micronaut:
  application:
    name: audioStreamer
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
