micronaut:
  application:
    name: micometers
  metrics:
    export:
      graphite:
        enabled: true
        host: localhost
        port: 2004
        step: PT1M
      statsd:
        enabled: true
        flavor: datadog
        host: localhost
        port: 8125
        step: PT1M
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
