  micronaut:
    application:
      name: JWTKotlinMongo
    executors:
      scheduled:
        type: scheduled
        core-pool-size: 30
    security:
      authentication: bearer
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
          generator:
            refresh-token:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
              enabled: true
            access-token:
              expiration: 3000000
      endpoints:
        login:
          path: "/api/security/login"
        logout:
          path: "/api/security/logout"
  mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
