

micronaut:
  application:
    name: demo

---
#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/hhDB
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: 'Hello@1234'
    schema-generate: CREATE_DROP
    dialect: MYSQL
---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**


---
micronaut:
  #  server:
  #    ssl:
  #      enabled: 'true'
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        generator:
          access-token:
            expiration: 23222222
    basic-auth:
      enabled: true
    enabled: true
