micronaut:
  application:
    name: micronautThymeleaf

---
micronaut:
  router:
    static-resources:
      default:
        mapping: "/static/**"
      '*':
        paths:
          - "classpath:static"
        enabled: true