
micronaut:
  application:
    name: microStreamCache
netty:
  default:
    allocator:
      max-order: 3

---
---
micronaut.server.port: 8080
---

---
micronaut:
  metrics:
    enabled: true
    sensitive: Boolean

---
endpoints:
  prometheus:
    sensitive: false
micronaut:
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1

---
graphql:
  graphiql.enabled: true

---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**


---
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
microstream:
  storage:
    Fruit:
      storage-directory: 'd:/Hello/MicrostreaCache'
      root-class: 'io.hashimati.microstream.FruitData'
      channel-count: 4